version: "3.9"

services:
  app:
    build: .
    container_name: lumen_app
    restart: always
    ports:
      - "8000:8000"
    volumes:
      - ./app:/var/www
    depends_on:
      - db

  db:
    image: postgres:15
    container_name: postgresql_db
    restart: always
    environment:
      POSTGRES_DB: postgresql_db
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root123
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data:
