version: "3.9"

services:
  app:
    build: .
    container_name: lumen_app
    restart: always
    ports:
      - "8000:8000"
    volumes:
      - ./app:/var/www
    depends_on:
      - db
      - mongo_db

  db:
    image: postgres:15
    container_name: postgresql_db
    restart: always
    environment:
      POSTGRES_DB: postgres_schema
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root123
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    env_file:
      - .env

  mongo_db:
    image: mongo:6
    container_name: mongo_db
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root123
      MONGO_INITDB_DATABASE: mongo_schema
    ports:
      - "27017:27017"

volumes:
  db_data:
  mongo_data:
